PO_Shop_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('admin/', admin.site.urls),
    path('Shop/', include('PoShopApp.urls', namespace="Shop")),
    path('Users/', include('Users.urls', namespace="Users")),
    path('Users/', include("django.contrib.auth.urls")),
    path('signin/<int:pk>', views.HomePage.as_view(), name='signin'),
]

PoShopApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'PoShopApp'

urlpatterns = [
    #equipment cbv's
    path('', views.EquipmentListView.as_view(), name="equipment_list"),
    path('equipment/<int:pk>/', views.EquipmentDetailView.as_view(), name='equipment_detail'),
    path('equipment/new/', views.CreateEquipmentView.as_view(), name='equipment_new'),
    path('equipment/<int:pk>/edit/', views.EquipmentUpdateView.as_view(), name='equipment_edit'),
    path('equipment/<int:pk>/remove/', views.EquipmentDeleteView.as_view(), name='equipment_remove'),
    #basket cbv's
    path('basket/', views.BasketListView.as_view(), name='order_list'),
    path('basket/<int:pk>/', views.BasketDetailView.as_view(), name='order_detail'),
    path('basket/<int:pk>/remove/', views.BasketDeleteView.as_view(), name='order_remove'),
    #function based views equipment
    path('equipment/<int:pk>/basket/', views.add_item_to_basket, name='add_item_to_basket'),
    path('basket/<int:pk>/approved', views.approve_order, name='approve_order'),
]

Users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Users'

urlpatterns = [
    path('signup/', views.SignIn.as_view(), name='signin'),
    path('login/', auth_views.LoginView.as_view(template_name="Users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('more/<int:pk>/', views.ProfileUpdateView.as_view(), name='more_info'),
    # path('account/<int:pk>', views.account_page, name='account'),
]

PoShopApp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from Users.models import User
# Create your models here.


class EquipmentCategories(models.TextChoices):
    FISHING_ROD = 'Fishing Rod'
    SPINNING_WHEEL = 'Spinning Wheel'
    CHAIR = 'Chair'
    NATURAL_BAIT = 'Natural Bait'
    CRANKBAIT = 'Crankbait'
    TWISTER = 'Twister'
    RUBBER_BAIT = 'Rubber Bait'
    WOBBLERS = 'Wobblers'
  
class Equipment(models.Model):
        
    category = models.CharField(
           max_length=50,
           choices=EquipmentCategories.choices
    )
    brand = models.CharField(max_length=64, null=True, default='Null')
    name = models.CharField(max_length=128)
    price = models.FloatField(default=0,
                                        validators=[MinValueValidator(0),
                                        MaxValueValidator(1000)])
    
    def get_absolute_url(self):
        return reverse("Shop:equipment_detail", kwargs={"pk": self.pk})
    
    def __str__(self) -> str:
        return self.name
    

class Order(models.Model):
    customer = models.ForeignKey(User, null=True, on_delete=models.PROTECT)
    orderdate = models.DateTimeField(blank=True, null=True)
    approved_order = models.BooleanField(default=False, blank=True, null=True)
    item = models.ForeignKey('PoShopApp.Equipment', related_name='basket_items', on_delete=models.CASCADE, null=True)
    
    def get_absolute_url(self):
        return reverse("Shop:order_detail", kwargs={"pk": self.pk})
    
    def add_to_basket(self):
        self.save()
    
    def approve_order(self):
        self.approved_order = timezone.now()
        self.approved_order = True
        self.save()
        return self.filter(approved_order=True)
    
    def __str__(self) -> str:
        return str(self.orderdate) + "  " + self.customer.username
    

PoShopApp/forms.py
from django import forms
from django.core import validators
from .models import Equipment

class ShopForm(forms.ModelForm):
    class Meta():
        model = Equipment
        fields = ('category', 'brand', 'name', 'price')

PoShopApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

# pip install django-braces
# from braces.views import SelectRelatedMixin
# from . import forms
from .models import (Equipment, Order)
from .forms import ShopForm

# #Create your views here.
#EQUIPMENT SECTION
class EquipmentListView(ListView):
    model = Equipment
    
    def get_queryset(self):
        return Equipment.objects.order_by('-category')
    
class EquipmentDetailView(DetailView):
    model=Equipment
    
class CreateEquipmentView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'Shop/equipment_detail.html'
    form_class = ShopForm
    model = Equipment
    
class EquipmentUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'Shop/equipment_detail.html'
    form_class = ShopForm
    model = Equipment
    
class EquipmentDeleteView(LoginRequiredMixin, DeleteView):
    model = Equipment
    success_url = reverse_lazy('Shop:order_list')

#BASKET SECTION
class BasketListView(ListView):
    model = Order
    
    def get_queryset(self):
        return Order.objects.order_by('-item')
    
class BasketDetailView(DetailView):
    model=Order
    
    
class BasketDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('Shop:order_list')

## function based views
@login_required
def add_item_to_basket(request, pk):   
    item = get_object_or_404(Equipment, pk=pk)
    basket, created = Order.objects.get_or_create(customer=request.user, item=item)
    basket.add_to_basket()
    return redirect('Shop:equipment_list')

@login_required
def approve_order(request, pk):
    item = get_object_or_404(Order, pk=pk)
    item.approved_order = True
    item.save()
    return redirect('Shop:equipment_list')    
    

PoShopApp/templates/PoShopApp/equipment_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock body_block %}

PoShopApp/templates/PoShopApp/equipment_detail.html
{% extends 'base.html' %}
{% block body_block %}
    <h1 class="posttitle loader">{{equipment.name}}</h1>
    <h2>{{equipment.price}} PLN</h2>
    {% if user.is_authenticated and user.profile.account_type == "Salesman" %}
        <a class="btn btn-primary" href="{% url 'Shop:equipment_edit' pk=equipment.pk %}">
            Edit
        </a>
        
        <a class="btn btn-primary" href="{% url 'Shop:equipment_remove' pk=equipment.pk %}">
            Remove
        </a>

    {% else %}
        <a class="btn btn-primary" href="{% url 'Shop:add_item_to_basket' pk=equipment.pk %}">Add To Basket</a>
    {% endif %}

    <hr>
{% comment %} 
    <a class="btn btn-primary btn-comment" href="{% url 'add_comment_to_post' pk=post.pk %}">Add Comment</a>

    <div class="container">
        <br>
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved_comment %}
                {{comment.created_at}}
                {% if not comment.approved_comment %}
                <a class="btn btn-primary" href="{% url 'comment_remove' pk=comment.pk %}">Remove</a>
                <a class="btn btn-primary" href="{% url 'comment_approve' pk=comment.pk %}">Add</a>
                {% endif %}

                <p>{{ comment.text|safe|linebreaks }}</p>
                <p>Posted On: <strong>{{comment.create_date}}</strong> By: <strong>{{comment.author}}</strong></p>
            {% endif %}
            {% empty %}
            <p>No Comments Posted!</p>
        {% endfor %}
    </div>  {% endcomment %}
{% endblock body_block %}

PoShopApp/templates/PoShopApp/equipment_form.html
{% extends 'base.html' %}
{% block body_block %}
    <h1>New Product</h1>
    <form class="equipment-form" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock body_block %}

PoShopApp/templates/PoShopApp/equipment_list.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="/home/mioshek/Programming_Stuff/Programming/Python/SoftwareLibraries/Django/PO_Shop_Project/static/css/shop_view.css">
{% block body_block %}
    {% comment %} <div class="container"> {% endcomment %}
        {% if user.is_authenticated and user.profile.account_type == "Salesman"%}
        <a class="btn btn-primary btn-comment" href="{% url 'Shop:equipment_new' %}">Add Item</a>
        {% endif %}

    <div class="parent-flex">
        {% for equipment in equipment_list %}
            <div class="flex-item">
                <h4><a href="{% url 'Shop:equipment_detail' pk=equipment.pk%}"> {{equipment.name}}</a></h4>
                <p>Brand: {{equipment.brand}}</p>
                <p>Price: {{equipment.price}} PLN</p>
                <p>Category: {{ equipment.category }}</p>
                <br>
            </div>
        {% endfor %}
    </div>

        
    {% comment %} </div> {% endcomment %}
{% endblock body_block %}

PoShopApp/templates/PoShopApp/item.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>item.HTML</h1>
    </div>
{% endblock body_block %}

PoShopApp/templates/PoShopApp/order_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock body_block %}

PoShopApp/templates/PoShopApp/order_detail.html
{% extends 'base.html' %}
{% block body_block %}
    <h1 class="posttitle loader">{{equipment.name}}</h1>
    <h2>{{equipment.price}} PLN</h2>
    {% if user.is_authenticated %}

        <a class="btn btn-primary" href="{% url 'Shop:order_remove' pk=order.pk %}">Remove From Basket</a>
        
    {% endif %}

    <hr>
{% endblock body_block %}

PoShopApp/templates/PoShopApp/order_list.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="/home/mioshek/Programming_Stuff/Programming/Python/SoftwareLibraries/Django/PO_Shop_Project/static/css/shop_view.css">
{% block body_block %}
    {% comment %} <div class="container"> {% endcomment %}
    <div class="parent-flex">
        {% for order in order_list %}
            {% if order.customer.username == user.username %}
                <div class="flex-item">
                    <h4><a href="{% url 'Shop:order_detail' pk=order.pk%}"> {{order.item.name}}</a></h4>
                    <p>Brand: {{order.item.brand}}</p>
                    <p>Price: <b class="price" id="{{ forloop.counter }}">{{order.item.price}}</b> PLN</p>
                    <p>Category: {{ order.item.category }}</p>
                    <br>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if user.profile.account_type == "Salesman" %}
        {% for order in order_list %}
            <h2>{{order.item}}</h2>
            <h3>{{order.customer.username}}</h3>
            <form method="POST" action="{% url 'Shop:approve_order' pk=order.pk %}">
                {% csrf_token %}
                <button type="submit", class="btn btn-success" value="approve">Approve Order</button>
            </form>
            <br>
            <br>
        {% endfor %}
    {% else %}
    <script>
        function get_price(){
        var all = document.getElementsByClassName("price");
        var price = 0;
        for (var i=1, max=all.length +1; i < max; i++){
            var el = document.getElementById(i).innerHTML;
            price += parseInt(el);

        }
        document.getElementById('myh').innerHTML = "Total Price: " +price + "PLN";
    }
    </script>
        <h2 id="myh"> <button type="button" onclick="get_price();">Get Price</button></h2>
    {% endif %}
    
        
    {% comment %} </div> {% endcomment %}
{% endblock body_block %}

PoShopApp/templates/PoShopApp/shop.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>INDEX.HTML</h1>
    </div>
{% endblock body_block %}