PO_Shop_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('admin/', admin.site.urls),
    path('Shop/', include('PoShopApp.urls', namespace="Shop")),
    path('Users/', include('Users.urls', namespace="Users")),
    path('Users/', include("django.contrib.auth.urls")),
    path('signin/<int:pk>', views.HomePage.as_view(), name='signin'),
]

PoShopApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'PoShopApp'

urlpatterns = [
    #equipment cbv's
    path('', views.EquipmentListView.as_view(), name="equipment_list"),
    path('equipment/<int:pk>/', views.EquipmentDetailView.as_view(), name='equipment_detail'),
    path('equipment/new/', views.CreateEquipmentView.as_view(), name='equipment_new'),
    path('equipment/<int:pk>/edit/', views.EquipmentUpdateView.as_view(), name='equipment_edit'),
    path('equipment/<int:pk>/remove/', views.EquipmentDeleteView.as_view(), name='equipment_remove'),
    #basket cbv's
    path('basket/', views.BasketListView.as_view(), name='order_list'),
    path('basket/<int:pk>/', views.BasketDetailView.as_view(), name='order_detail'),
    path('basket/<int:pk>/remove/', views.BasketDeleteView.as_view(), name='order_remove'),
    #function based views equipment
    path('equipment/<int:pk>/basket/', views.add_item_to_basket, name='add_item_to_basket'),
    path('basket/<int:pk>/approved', views.approve_order, name='approve_order'),
]

Users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Users'

urlpatterns = [
    path('signup/', views.SignIn.as_view(), name='signin'),
    path('login/', auth_views.LoginView.as_view(template_name="Users/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('more/<int:pk>/', views.ProfileUpdateView.as_view(), name='more_info'),
    # path('account/<int:pk>', views.account_page, name='account'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fish Shop</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li><a class="navbar-brand" href="{% url 'test'%}" class="btn btn-simple">{{request.user.username}}</a></li>
                <li><a class="navbar-link" href="{% url 'Shop:equipment_list'%}" class="btn btn-simple">Shop</a></li>
                <li><a class="navbar-link" href="{% url 'Users:logout' %}" class="btn btn-simple">Logout</a></li>
                {% else %}
                <li><a class="navbar-brand" href="{% url 'Users:login' %}" class="btn btn-simple">Home</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'Users:signin' %}" class="btn btn-simple">Sign In</a></li>
                <li><a class="navbar-link" href="{% url 'Users:login' %}" class="btn btn-simple">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}

    <h1>Welcome To Shop!</h1>
    <h2>Please <a href="{% url 'Users:login'%}">Log In</a> To Get Started!</h2>

{% endblock %}

templates/test.html
{% extends "base.html" %} 
{% block body_block %}
<div class="container">
  <h1>You are now logged in {{user.username|lower|capfirst}} !</h1>
  <h2>Check <a href="{% url 'Shop:order_list' %}">Basket</a></h2>
  <h2>Add More Info To Your <a href="{% url 'Users:more_info' pk=user.id %}">Profile</a></h2>
  {% comment %} <h2><a href="{% url 'Users:account'%}">Go to Profile</a></h2> {% endcomment %}

</div>

{% endblock %}

templates/thanks.html
{% comment %} {% extends "base.html" %} {% endcomment %}
{% block body_block %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}